name: Build PWEM Indexes
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Generate PWEM indexes & catalog
        run: python scripts/pwem_generate.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "pwem-bot"
          author_email: "pwem-bot@users.noreply.github.com"
          message: "chore: auto-generate PWEM indexes & catalog"
